name: Feature Request
description: Suggest a new feature or improvement
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem would this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature you would like to see
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
